# Generated by Django 3.1.6 on 2021-02-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maruti',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_arena', models.CharField(max_length=200)),
                ('model_nexa', models.CharField(max_length=200)),
            ],
        ),
    ]
