# Generated by Django 3.1.6 on 2021-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0002_auto_20210203_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='maruti',
            name='car_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
