# Generated by Django 3.1.6 on 2021-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0003_maruti_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='maruti_nexa',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('car_name', models.CharField(default='', max_length=100)),
                ('ex_showroom_price', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='maruti',
            new_name='maruti_arena',
        ),
        migrations.RenameField(
            model_name='maruti_arena',
            old_name='model_category',
            new_name='category',
        ),
    ]
