# Generated by Django 3.1.6 on 2021-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0004_auto_20210203_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='maruti_arena',
            name='main_img',
            field=models.ImageField(default='', upload_to='car_data/images'),
        ),
        migrations.AddField(
            model_name='maruti_arena',
            name='price_in_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='main_img',
            field=models.ImageField(default='', upload_to='car_data/images'),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='price_in_city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
