# Generated by Django 3.1.6 on 2021-02-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0007_auto_20210203_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='maruti_nexa',
            name='ARAI_Mileage',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Body_Type',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Boot_Space',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Engine_Displacement',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Fuel_Tank_Capacity',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Fuel_Type',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Max_Power',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Max_Torque',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Seating_Capacity',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Service_Cost',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='TransmissionType',
            field=models.CharField(default='', max_length=400),
        ),
    ]
