# Generated by Django 3.1.6 on 2021-02-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0008_auto_20210203_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='maruti_nexa',
            name='Air_Conditioner',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Alloy_Wheels',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Anti_Lock_Braking_System',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Automatic_Climate_Control',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Driver_Airbag',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Fog_Lights_Front',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Passenger_Airbag',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Power_Steering',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maruti_nexa',
            name='Power_Windows_Front',
            field=models.CharField(default='', max_length=300),
        ),
    ]
