# Generated by Django 3.1.6 on 2021-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0010_tata_moter'),
    ]

    operations = [
        migrations.CreateModel(
            name='jaguar_moter',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_company', models.CharField(default='', max_length=200)),
                ('main_img', models.ImageField(default='', upload_to='car_data/images')),
                ('price_in_city', models.CharField(default='', max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('car_name', models.CharField(default='', max_length=100)),
                ('ex_showroom_price', models.CharField(max_length=200)),
                ('reviews', models.CharField(default='', max_length=500)),
                ('specs_features_and_price', models.TextField(default='')),
                ('first_img', models.ImageField(default='', upload_to='car_data/images')),
                ('second_img', models.ImageField(default='', upload_to='car_data/images')),
                ('third_img', models.ImageField(default='', upload_to='car_data/images')),
                ('ARAI_Mileage', models.CharField(default='', max_length=400)),
                ('Fuel_Type', models.CharField(default='', max_length=400)),
                ('Engine_Displacement', models.CharField(default='', max_length=400)),
                ('Max_Power', models.CharField(default='', max_length=400)),
                ('Max_Torque', models.CharField(default='', max_length=400)),
                ('Seating_Capacity', models.CharField(default='', max_length=400)),
                ('TransmissionType', models.CharField(default='', max_length=400)),
                ('Boot_Space', models.CharField(default='', max_length=400)),
                ('Fuel_Tank_Capacity', models.CharField(default='', max_length=400)),
                ('Body_Type', models.CharField(default='', max_length=400)),
                ('Service_Cost', models.CharField(default='', max_length=400)),
                ('Power_Windows_Front', models.CharField(default='', max_length=300)),
                ('Air_Conditioner', models.CharField(default='', max_length=300)),
                ('Passenger_Airbag', models.CharField(default='', max_length=300)),
                ('Fog_Lights_Front', models.CharField(default='', max_length=300)),
                ('Power_Steering', models.CharField(default='', max_length=300)),
                ('Anti_Lock_Braking_System', models.CharField(default='', max_length=300)),
                ('Driver_Airbag', models.CharField(default='', max_length=300)),
                ('Automatic_Climate_Control', models.CharField(default='', max_length=300)),
                ('Alloy_Wheels', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
