# Generated by Django 3.1.6 on 2021-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0012_mahindra_moter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_car',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('car_brand', models.CharField(max_length=200)),
                ('car_year', models.CharField(max_length=200)),
                ('CarModel', models.CharField(max_length=200)),
                ('KMsDriven', models.CharField(max_length=200)),
                ('ownership', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('Expacted_price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='car_data/sellcar_img/images')),
            ],
        ),
    ]
