# Generated by Django 3.1.6 on 2021-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0013_sell_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(upload_to='car_data/images'),
        ),
    ]
