# Generated by Django 3.1.6 on 2021-02-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0014_auto_20210207_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_car',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='sell_car',
            old_name='lastname',
            new_name='Lastname',
        ),
    ]
