# Generated by Django 3.1.6 on 2021-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0015_auto_20210207_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(upload_to='car_data\\sellerupload'),
        ),
    ]
