# Generated by Django 3.1.6 on 2021-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0016_auto_20210207_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(default='', upload_to='car_data/sellcar img'),
        ),
    ]
