# Generated by Django 3.1.6 on 2021-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0017_auto_20210207_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(default='', upload_to='car_data/sellcar_img'),
        ),
    ]
