# Generated by Django 3.1.6 on 2021-02-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0018_auto_20210207_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(default='', upload_to='car_data/sellerupload'),
        ),
    ]
