# Generated by Django 3.1.6 on 2021-02-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0021_auto_20210208_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
