# Generated by Django 3.1.6 on 2021-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0023_auto_20210208_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(upload_to='car_data/sellcar_upload'),
        ),
    ]
