# Generated by Django 3.1.6 on 2021-02-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0024_auto_20210208_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='image',
            field=models.ImageField(upload_to='car_data/upload_cars_img'),
        ),
    ]
