# Generated by Django 3.1.6 on 2021-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0025_auto_20210208_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_data/upimage')),
            ],
        ),
    ]
