# Generated by Django 3.1.6 on 2021-02-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0026_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='upimg'),
        ),
    ]
