# Generated by Django 3.1.6 on 2021-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0027_auto_20210208_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='dev'),
        ),
    ]
