# Generated by Django 3.1.6 on 2021-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0028_auto_20210208_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='image',
        ),
        migrations.AddField(
            model_name='upload',
            name='img',
            field=models.ImageField(default='', upload_to='car_data/upload'),
        ),
    ]
