# Generated by Django 3.1.6 on 2021-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0031_auto_20210208_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_car',
            name='image',
        ),
        migrations.AddField(
            model_name='sell_car',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='car_data/images/sellcar'),
        ),
    ]
