# Generated by Django 3.1.6 on 2021-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0032_auto_20210208_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_car',
            name='images',
            field=models.FilePathField(default='', path='\\media\\car_data\\sellcar'),
        ),
    ]
