# Generated by Django 3.1.6 on 2021-02-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0041_ford_moter_honda_moter_hundai_moter_nissan_moter_renult_moter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('Short_Summery', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
