# Generated by Django 3.1.6 on 2021-03-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0042_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell_car',
        ),
    ]
