# Generated by Django 3.1.6 on 2021-04-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0044_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_car_details',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
