# Generated by Django 3.1.6 on 2021-04-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_data', '0045_auto_20210405_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_car_details',
            name='date',
        ),
    ]
